name: 'magic42/deployphp-action'

description: 'Deploy with Deployer'

inputs:

  dep:
    required: true
    description: The command.

  self-hosted:
    required: false
    default: 'false'
    description: Whether the action is running on a self-hosted runner.

  access-token:
    required: false
    default: ''
    description: The access token for the repository.

  access-token-user:
    required: false
    default: ''
    description: The user for the access token.

  private-key:
    required: false
    default: ''
    description: The private key for connecting to remote hosts.

  known-hosts:
    required: false
    default: ''
    description: Content of `~/.ssh/known_hosts` file.

  ssh-config:
    required: false
    default: ''
    description: The SSH configuration

  deployer-version:
    required: false
    default: ''
    description: Deployer version to download from deployer.org.

  deployer-binary:
    required: false
    default: ''
    description: Path to local Deployer binary.

  ansi:
    required: false
    default: 'true'
    description: Whether to enable ANSI output.

  verbosity:
    required: false
    default: '-v'
    description: Verbosity level Can be -v, -vv or -vvv.

runs:
  using: 'node12'
  main: 'index.js'

branding:
  color: blue
  icon: send
